export const FORM_STEPS = [
  {
    name: "Personal Information",
    fields: ["name", "mobileNumber", "village", "id", "email", "gender", "nationality"],
  },
  {
    name: "Additional Details",
    fields: [
      "bloodGroup",
      "birthDate",
      "marriageDate",
      "education",
      "currentAddress",
      "city",
      "district",
      "state",
      "regionalAssembly",
      "localPanchayatName",
      "localPanchayat",
      "subLocalPanchayat",
    ],
  },
  { 
    name: "Family Information", 
    fields: ["familyDetails"] 
  },
  {
    name: "Biographical Details",
    fields: ["manglik", "grah", "handicap", "gotra", "aakna"],
  },
  {
    name: "Work Information",
    fields: [
      "occupation",
      "companyName",
      "workArea",
      "industrySector",
      "businessSize",
      "workType",
      "employmentType"
    ],
  },
  {
    name: "Final Submission",
    fields: ["suggestions"],
  },
];

export const REQUIRED_FIELDS = [
  "name", 
  "mobileNumber", 
  "village", 
  "email", 
  "bloodGroup",
  "birthDate", 
  "education", 
  "currentAddress", 
  "gender",
  "nationality",
  "state", 
  "occupation", 
  "companyName", 
  "workArea", 
  "industrySector",
  "businessSize", 
  "workType", 
  "employmentType"
];

export const INITIAL_FORM_STATE = {
  name: "",
  mobileNumber: "",
  display_picture: null,
  village: "",
  email: "",
  nationality: "",
  bloodGroup: "",
  birthDate: "",
  marriageDate: "",
  education: "",
  currentAddress: "",
  city: "",
  district: "",
  state: "",
  familyDetails: [],
  manglik: "",
  grah: "",
  handicap: "",
  gotra: "",
  aakna: "",
  occupation: "",
  companyName: "",
  workArea: "",
  industrySector: "",
  businessSize: "",
  workType: "",
  employmentType: "",
  suggestions: "",
  referenceBy: "",
  gender: "",
  isMarried: "Unmarried",
  marriageToAnotherCaste: "Same Caste Marriage",
  regionalAssembly: "",
  localPanchayat: "",
  localPanchayatName: "",
  subLocalPanchayat: "",
}; 